<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('students')->insert([
            [
                'first_name' => 'Amanda',
                'last_name' => 'Jones',
                'siswamail' => 's2139201@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2021/2022',
                'semester' => 6,
                'program' => 'MSE (ST)',
                'research' => 'Analyzing the effectiveness of agile methodologies in large-scale software development projects',
                'task' => 'Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 82,
                'track_status' => 'On Track',
                'cgpa' => 3.82,
                'matric_number' => 'S2139201',
                'remarks' => '',
            ],
            [
                'first_name' => 'Brandon',
                'last_name' => 'Cliff',
                'siswamail' => 's2102392@siswa.um.edu.my',
                'supervisor' => 'Red',
                'status' => 'Active',
                'intake' => 'Sem 1, 2021/2022',
                'semester' => 6,
                'program' => 'MCS (AC)',
                'research' => 'Investigating the use of microservices architecture for building scalable and resilient software systems',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 62,
                'track_status' => 'Very Delayed',
                'cgpa' => 3.74,
                'matric_number' => 'S2102392',
                'remarks' => '',
            ],
            [
                'first_name' => 'Charlie',
                'last_name' => 'Brown',
                'siswamail' => 's2102322@siswa.um.edu.my',
                'supervisor' => 'Blue',
                'status' => 'Inactive',
                'intake' => 'Sem 1, 2021/2022',
                'semester' => 6,
                'program' => 'MCS (AC)',
                'research' => 'Investigating the impact of agile practices on software development',
                'task' => 'Candidature Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 74,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.74,
                'matric_number' => 'S2102322',
                'remarks' => '',
            ],
            [
                'first_name' => 'Daisy',
                'last_name' => 'Hayn',
                'siswamail' => 's2102092@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2021/2022',
                'semester' => 6,
                'program' => 'MSE (ST)',
                'research' => 'Exploring the use of blockchain for secure software development',
                'task' => 'Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 78,
                'track_status' => 'On Track',
                'cgpa' => 3.92,
                'matric_number' => 'S2102092',
                'remarks' => '',
            ],
            [
                'first_name' => 'Eve',
                'last_name' => 'Flint',
                'siswamail' => 's2102022@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2021/2022',
                'semester' => 6,
                'program' => 'MSE (ST)',
                'research' => 'Exploring machine learning techniques for software defect prediction',
                'task' => 'Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 90,
                'track_status' => 'On Track',
                'cgpa' => 3.62,
                'matric_number' => 'S2102022',
                'remarks' => '',
            ],
            [
                'first_name' => 'Dylan',
                'last_name' => 'Fate',
                'siswamail' => 's2102032@siswa.um.edu.my',
                'supervisor' => 'Blue',
                'status' => 'Inactive',
                'intake' => 'Sem 2, 2021/2022',
                'semester' => 5,
                'program' => 'MCS (AC)',
                'research' => 'Investigating the impact of DevOps practices on software development productivity',
                'task' => 'Candidature Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 58,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.73,
                'matric_number' => 'S2102032',
                'remarks' => '',
            ],
            [
                'first_name' => 'Ellie',
                'last_name' => 'Zayn',
                'siswamail' => 's2102332@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 2, 2021/2022',
                'semester' => 5,
                'program' => 'MCS (AC)',
                'research' => 'Investigating the impact of DevOps practices on software development productivity',
                'task' => 'Candidature Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 58,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.83,
                'matric_number' => 'S2102332',
                'remarks' => '',
            ],
            [
                'first_name' => 'Sebin',
                'last_name' => 'Hwang',
                'siswamail' => 's2117072@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 2, 2021/2022',
                'semester' => 5,
                'program' => 'MSE (ST)',
                'research' => 'Investigating the impact of DevOps practices on software development productivity',
                'task' => 'Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 70,
                'track_status' => 'On Track',
                'cgpa' => 3.93,
                'matric_number' => 'S2117072',
                'remarks' => '',
            ],
            [
                'first_name' => 'Fred',
                'last_name' => 'Drake',
                'siswamail' => 's2105432@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2022/2023',
                'semester' => 4,
                'program' => 'MSE (ST)',
                'research' => 'Analyzing the effectiveness of agile methodologies in large-scale software development projects',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 36,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.87,
                'matric_number' => 'S2105432',
                'remarks' => '',
            ],
            [
                'first_name' => 'Ginny',
                'last_name' => 'Weasley',
                'siswamail' => 's2105492@siswa.um.edu.my',
                'supervisor' => 'Yellow',
                'status' => 'Inactive',
                'intake' => 'Sem 1, 2022/2023',
                'semester' => 4,
                'program' => 'MCS (AC)',
                'research' => 'Analyzing the effectiveness of agile methodologies in large-scale software development projects',
                'task' => 'Draft of Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 49,
                'track_status' => 'On Track',
                'cgpa' => 3.70,
                'matric_number' => 'S2105492',
                'remarks' => '',
            ],
            [
                'first_name' => 'Hank',
                'last_name' => 'Thomas',
                'siswamail' => 's2158492@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2022/2023',
                'semester' => 4,
                'program' => 'MSE (ST)',
                'research' => 'Investigating the use of microservices for building scalable and resilient software',
                'task' => 'Draft of Dissertation',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 52,
                'track_status' => 'On Track',
                'cgpa' => 3.89,
                'matric_number' => 'S2158492',
                'remarks' => '',
            ],
            [
                'first_name' => 'Ivy',
                'last_name' => 'Lee',
                'siswamail' => 's2159692@siswa.um.edu.my',
                'supervisor' => 'Pink',
                'status' => 'Active',
                'intake' => 'Sem 1, 2022/2023',
                'semester' => 4,
                'program' => 'MSE (ST)',
                'research' => 'Exploring blockchain technology for secure software development',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 41,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.68,
                'matric_number' => 'S2159692',
                'remarks' => '',
            ],
            [
                'first_name' => 'Iris',
                'last_name' => 'Gray',
                'siswamail' => 's2151302@siswa.um.edu.my',
                'supervisor' => 'Blue',
                'status' => 'Active',
                'intake' => 'Sem 2, 2022/2023',
                'semester' => 3,
                'program' => 'MSE (ST)',
                'research' => 'Analyzing the effectiveness of agile methodologies in large-scale software development projects',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 45,
                'track_status' => 'On Track',
                'cgpa' => 3.97,
                'matric_number' => 'S2151302',
                'remarks' => '',
            ],
            [
                'first_name' => 'Harry',
                'last_name' => 'Styles',
                'siswamail' => '22151302@siswa.um.edu.my',
                'supervisor' => 'Pink',
                'status' => 'Active',
                'intake' => 'Sem 1, 2023/2024',
                'semester' => 2,
                'program' => 'MCS (AC)',
                'research' => 'Exploring the use of blockchain technology for secure software supply chain management',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 32,
                'track_status' => 'On Track',
                'cgpa' => 3.48,
                'matric_number' => '22151302',
                'remarks' => '',
            ],
            [
                'first_name' => 'Jack',
                'last_name' => 'Smith',
                'siswamail' => '22091302@siswa.um.edu.my',
                'supervisor' => 'Green',
                'status' => 'Active',
                'intake' => 'Sem 1, 2023/2024',
                'semester' => 2,
                'program' => 'MSE (ST)',
                'research' => 'Investigating the use of machine learning for software defect prediction',
                'task' => 'Proposal Defence',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 27,
                'track_status' => 'On Track',
                'cgpa' => 3.88,
                'matric_number' => '22091302',
                'remarks' => '',
            ],
            [
                'first_name' => 'Kate',
                'last_name' => 'Trace',
                'siswamail' => '22181302@siswa.um.edu.my',
                'supervisor' => 'Red',
                'status' => 'Active',
                'intake' => 'Sem 1, 2023/2024',
                'semester' => 2,
                'program' => 'MSE (ST)',
                'research' => 'Analyzing the impact of agile methodologies on software development projects',
                'task' => 'Core Courses',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 15,
                'track_status' => 'Slightly Delayed',
                'cgpa' => 3.95,
                'matric_number' => '22181302',
                'remarks' => '',
            ],
            [
                'first_name' => 'Jim',
                'last_name' => 'Brint',
                'siswamail' => '22821305@siswa.um.edu.my',
                'supervisor' => 'Orange',
                'status' => 'Active',
                'intake' => 'Sem 2, 2023/2024',
                'semester' => 1,
                'program' => 'MSE (ST)',
                'research' => 'Investigating the impact of DevOps practices on software development productivity',
                'task' => 'Core Courses',
                'profile_pic' => '/images/profile-pic.png',
                'progress' => 15,
                'track_status' => 'On Track',
                'cgpa' => 3.66,
                'matric_number' => '22821305',
                'remarks' => '',
            ]
        ]);
    }
}
